### ISSUE TITLE
Methods with the same name as their class will not be constructors in a future version of PHP

### ISSUE THREAD

**Issue by michaellindman** [vamsiikrishna/cimarkdown#4]
I encountered a message when using Cimarkdown on PHP7.0 which states that:

> **Deprecated**: Methods with the same name as their class will not be constructors in a future version of PHP; Markdown_Parser has a deprecated constructor in **Cimarkdown.php** on line **204**

This was in relation to the fact that the naming convention for constructors in PHP5 and above has changed to use `__construct()` instead of the name of the class. As of yet everything works as intended apart from showing the message.

I did manage to remove the message by changing the function on line 231 from `Markdown_Parser` to `__construct()` which seems to have resolved the issue without any adverse effects.

**Comment by vamsiikrishna** [comment]
Thanks for reporting this . 
can you please send a pull request with the changes you have made ?
